services:

  db:
    image: mariadb:10.11
    container_name: nextcloud_db
    restart: always
    command: --transaction-isolation=READ-COMMITTED --log-bin=off
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    # Healthcheck: nextcloud не стартует пока БД не готова принимать соединения
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  nextcloud:
    build: .
    container_name: nextcloud_app
    restart: always
    volumes:
      - F:/NextcloudData:/var/www/html/data   # Файлы пользователей
      - F:/SharedNAS:/mnt/nas                 # Общая папка
      - nextcloud_config:/var/www/html/config
      - nextcloud_apps:/var/www/html/custom_apps
      - tmp_volume:/tmp
    environment:
      NEXTCLOUD_TRUSTED_DOMAINS: "nas.nehade.xyz localhost 127.0.0.1"
      MYSQL_HOST: db
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      PHP_PM_MAX_CHILDREN: 20
      PHP_PM_START_SERVERS: 5
      EXIFTOOL_NO_EXEC: 1
    depends_on:
      db:
        condition: service_healthy   # ожидаем запуск бд
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/status.php"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  # ==================== CRON ДЛЯ NEXTCLOUD ====================
  nextcloud-cron:
    build: .
    container_name: nextcloud_cron
    restart: always
    entrypoint: /cron.sh
    volumes:
      - F:/NextcloudData:/var/www/html/data
      - F:/SharedNAS:/mnt/nas
      - nextcloud_config:/var/www/html/config
      - nextcloud_apps:/var/www/html/custom_apps
      - tmp_volume:/tmp
    environment:
      MYSQL_HOST: db
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      db:
        condition: service_healthy
      nextcloud:
        condition: service_healthy   #ждём запуска некстклауд

  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:2.14.0
    container_name: nginx_pm
    restart: always
    ports:
      - "80:80"    # HTTP (редиректит на HTTPS)
      - "443:443"  # HTTPS
      - "81:81"    # Админка NPM 
    volumes:
      - npm_data:/data
      - npm_letsencrypt:/etc/letsencrypt
ча
volumes:
  db_data:
  nextcloud_config:
  nextcloud_apps:
  npm_data:
  npm_letsencrypt:
  tmp_volume:
