services:
  talk:
    image: ghcr.io/nextcloud-releases/aio-talk:latest
    container_name: talk_hpb
    init: true
    ports:
      - "3478:3478/tcp"   # Порт для Turn-сервера
      - "3478:3478/udp"
      - "8181:8081/tcp"   # Порт для Сигнального сервера
    environment:
      - NC_DOMAIN=nas.nehade.xyz # Ваш домен Nextcloud
      - TALK_HOST=signal.nehade.xyz # Домен для HPB
      - TURN_SECRET=${TURN_SECRET}
      - SIGNALING_SECRET=${SIGNALING_SECRET}
      - INTERNAL_SECRET=${INTERNAL_SECRET}
      - TZ=Europe/Moscow
      - TALK_PORT=3478
    restart: unless-stopped
